apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-app-multi-components-repo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-app-multi-components-repo
    app.kubernetes.io/part-of: multi-components-repo
  name: nodejs-app-multi-components-repo
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-app-multi-components-repo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-app-multi-components-repo
    spec:
      containers:
      - env:
        - name: secondEnvVar
          value: "3000"
        image: quay.io/hacdev/xkq5co81-tenant/multi-components-repo/nodejs-app-multi-components-repo@sha256:2d91ecab859722aa321d109c7309aa07cdb9c604b8b1f78325abb22e479bfa67
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
